name: Linux Head Command Autograding

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:

  test:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4


    - name: Give Permission
      run: |
        chmod +x starter/solution.sh
        chmod +x tests/test_head.sh


    - name: Run Test Cases
      run: |
        bash tests/test_head.sh
